### PR TITLE
Fixes stone ranks

### LINKED ISSUE #22: Soulstone / Healthstone Ranks not working
The ranks for the stones doesnt seem to work. I'm Lvl 18 and have "Create Soulstone (Minor)", however, the button on the sphere doesnt work (left or right click). If I change the SpellID in Spells.lua to the Minor version (ID 693), the button works fine.

Same with Healthstone. I can create a Healthstone (Minor), but with a left click instead of a right click on the sphere button.

Thanks
Love the addon and ur work. much appreciated

### PR DESCRIPTION
**Pull request by llyama**
This should fix #22 for the localisations that support it.

It probably does need a rework though.

### CODE REVIEW

File: Necrosis/Necrosis.lua [hunk 1]
```diff
@@ -2126,31 +2126,31 @@ function Necrosis:StoneToRank(spellName)
 		return self.Translation.Misc.Rank .. " 1"
 	end
 	if (spellName:find(self.Translation.StoneRank.Major)) then
-		return self.Translation.Misc.Rank .. " 2"
+		return self.Translation.Misc.Rank .. " 5"
 	end
 	if (spellName:find(self.Translation.StoneRank.Lesser)) then
-		return self.Translation.Misc.Rank .. " 4"
+		return self.Translation.Misc.Rank .. " 2"
```
Comment (Nezz) [inline Necrosis/Necrosis.lua]: Thanks for the fix. This fixes the issue where a lesser healthstone was created when a higher rank is available.

Comment (llyama) [reply Necrosis/Necrosis.lua]: That alone doesn't actually fix the healthstone problem. I fixed this first but it didn't change anything.

It's also the change of spellid in spells.lua from Healthstone (Lesser) to just Healthstone. Without changing that the ranking code looks for a higher rank of "Healthstone (Lesser)" which doesn't work.

Comment (robert388) [reply Necrosis/Necrosis.lua]: Seems to work thanks!
